### ISSUE TITLE
Use todo.txt's default config file

### ISSUE THREAD

**Issue by jose1711** [hugokernel/todofi.sh#2]
`todo.txt` uses `$HOME/.todo/config` as a default file for user configuration. i wonder what is the need of a separate configuration in `$HOME/.config/todo-txt.cfg`.

**Comment by hugokernel** [comment]
Hi,

Because since this PR https://github.com/todotxt/todo.txt-cli/pull/154, todo.txt read config file from XDG directories and I prefer that the configuration files be stored there.

todo.txt try to open config file in this order (source https://github.com/todotxt/todo.txt-cli/blob/master/todo.sh#L660):

1. `${TODOTXT_CFG_FILE:-$HOME/.todo/config}`
2. `$HOME/todo.cfg`
3. `$HOME/.todo.cfg`
4. `${XDG_CONFIG_HOME:-$HOME/.config}/todo/config`
5. `"$(dirname "$0")"/todo.cfg`
6. `From $TODOTXT_GLOBAL_CFG_FILE`

**Comment by jose1711** [comment]
OK, I am with you on this. So the proposed change is to replace `$HOME/.config/todo-txt.cfg` with `${XDG_CONFIG_HOME:-$HOME/.config}/todo/config`

**Comment by hugokernel** [comment]
Can you make a PR ?
